In [1]:
import pandas as pd
import numpy as np

In [2]:
df_2016 = pd.read_csv('./Resources/train_2016_v2.csv')
df_2017 = pd.read_csv('./Resources/train_2017.csv')
df_prop_2016 = pd.read_csv('./output/prop_2016_refilled.csv')
df_prop_2017 = pd.read_csv('./output/prop_2017_refilled.csv')

/local/home/ningzesun/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (32,34,48,54) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/local/home/ningzesun/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df_2016 = df_2016.merge(df_prop_2016, on = 'parcelid', how = 'left')
df_2017 = df_2017.merge(df_prop_2017, on = 'parcelid', how = 'left')

In [4]:
df = pd.concat([df_2016, df_2017])

/local/home/ningzesun/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [5]:
df = df.reset_index(drop = True)

In [8]:
columns = {'buildingqualitytypeid_fill': 'buildingqualitytypeid', 'lotsizesquarefeet_refill': 'lotsizesquarefeet',
          'propertycountylandusecode_fill': 'propertycountylandusecode', 'regionidcity_fill': 'regionidcity', 
          'regionidneighborhood_fill': 'regionidneighborhood', 'regionidzip_fill': 'regionidzip', 
          'unitcnt_fill': 'unitcnt', 'yearbuilt_fill':'yearbuilt'}
df = df.drop_duplicates(subset = ['parcelid', 'logerror'])
df.drop(['lotsizesquarefeet'], axis = 1, inplace = True)
final_list = ['buildingqualitytypeid', 'lotsizesquarefeet', 'propertycountylandusecode', 'regionidcity', 
             'regionidneighborhood', 'regionidzip', 'unitcnt', 'yearbuilt',
             'latitude', 'longitude', 'logerror']
df = df.rename(columns = columns)[final_list]
df.to_csv('./output/clean_final.csv', index = False)

/local/home/ningzesun/.local/lib/python3.6/site-packages/pandas/core/frame.py:4117: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [9]:
df

,buildingqualitytypeid,buildingqualitytypeid,lotsizesquarefeet,propertycountylandusecode,propertycountylandusecode,regionidcity,regionidcity,regionidneighborhood,regionidneighborhood,regionidzip,regionidzip,unitcnt,unitcnt,yearbuilt,latitude,longitude,logerror
0,4.0,4.0,7528.0,0100,2.0,12447.0,12447.0,31817.0,31817.0,96370.0,96370.0,1.0,1.0,1959.0,34.280990,-118.488536,0.027600
1,NaN,0.0,3643.0,1,125.0,32380.0,32380.0,NaN,403196.0,96962.0,96962.0,NaN,4.0,2014.0,33.668120,-117.677556,-0.168400
2,4.0,4.0,11423.0,0100,2.0,47019.0,47019.0,275411.0,275411.0,96293.0,96293.0,1.0,1.0,1940.0,34.136312,-118.175032,-0.004000
3,4.0,4.0,70859.0,010C,11.0,12447.0,12447.0,54300.0,54300.0,96222.0,96222.0,1.0,1.0,1987.0,33.755800,-118.309000,0.021800
4,NaN,4.0,6000.0,122,177.0,17686.0,17686.0,NaN,764109.0,96961.0,96961.0,NaN,2.0,1981.0,33.485643,-117.700234,-0.005000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183626,8.0,8.0,59487.0,010C,11.0,12447.0,12447.0,32368.0,32368.0,96415.0,96415.0,1.0,1.0,1980.0,34.202400,-118.502000,-0.002245
183627,6.0,6.0,47405.0,0100,2.0,12447.0,12447.0,27328.0,27328.0,96284.0,96284.0,1.0,1.0,1940.0,34.245368,-118.282383,0.020615
183628,NaN,0.0,12105.0,1111,138.0,27110.0,27110.0,NaN,37835.0,97116.0,97116.0,NaN,2.0,1964.0,34.300140,-118.706327,0.013209
183637,4.0,4.0,5074.0,0100,2.0,36502.0,36502.0,NaN,259606.0,96480.0,96480.0,1.0,1.0,1954.0,34.040895,-118.038169,0.037129
183638,6.0,6.0,6347.0,0100,2.0,14634.0,14634.0,NaN,763790.0,96171.0,96171.0,1.0,1.0,1955.0,33.937685,-117.996709,0.007204